### PR TITLE
Hibernate 5.3 integration improvements

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
This pull requests addresses some integration issues for Hibernate 5.3.

Note: this branch is still under development. It currently does compile, but I'm still testing it.

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
@beikov The integration test fails on the exact compilation failure I have tried to resolve. Are the test profiles set up for Hibernate 5.3 already?

**Comment by beikov** [comment]
Yeah actually I already started working on it on a branch but wasn't able to finish it yet: https://github.com/beikov/blaze-persistence/tree/hibernate-5.3-prep

**Comment by JWGmeligMeyling** [comment]
Anything in particular that you didn't get to resolve yet in your branch?

**Comment by beikov** [comment]
My local tests showed that it should work with this: https://github.com/Blazebit/blaze-persistence/pull/573

**Pull request closed without merging**
