### PR TITLE
Support of cachable CTE queries

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
Finally found the time to finish off my PR 😄

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
Done.

**Comment by beikov** [comment]
Perfect, I'll merge it as soon as the tests pass

**Comment by JWGmeligMeyling** [comment]
The oracle tests are failing with a missing JDBC driver, I suppose this is unrelated to the changes?

**Comment by beikov** [comment]
It's unrelated indeed, I fixed that on a different PR

**Pull request merged**
