### PR TITLE
Reproducer issue #519: Hibernate Subselect Entity not supported by EntityMetamodelImpl

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
The test fails because `entityPersister.getSubclassTableName(i)` returns `"( SELECT 5 as b, a.a_id FROM a )"`, and looking up the `Table` for this in `Database` returns `null`.  I think this is actually quite hard to resolve as it seems that Hibernate provides no way do determine the column types for this sub select result.

**Comment by JWGmeligMeyling** [comment]
I've changed the test because the Hibernate was invalid causing the reproducer to fail even with the bug fixed.

**Comment by JWGmeligMeyling** [comment]
The tests fail because the SQL query used in the test entity is not valid SQL for all database vendors. I think for example for MySQL, columns have to be wrapped between ` quotes. Perhaps we can come up with a SQL fragment that is valid across all database vendors. Otherwise we may have to restrict the test to be run only on a couple of databases instead.

**Comment by beikov** [comment]
Superseded by https://github.com/Blazebit/blaze-persistence/pull/525

**Pull request closed without merging**
