### PR TITLE
Test an EntityViewInheritance that is referenced from another EntityView

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
While trying to reproduce issue #456, I created the following test case. I don't think it reproduces the same problem, as it seems to fail much earlier in the proces. The error message thrown in the test is as follows:

```
java.lang.RuntimeException: Probably we did something wrong, please contact us if you see this message.

	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:362)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.getProxy(ProxyFactory.java:193)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.getProxy(ProxyFactory.java:110)
	at com.blazebit.persistence.view.impl.proxy.ReflectionInstantiator.getProxyClass(ReflectionInstantiator.java:74)
	at com.blazebit.persistence.view.impl.proxy.ReflectionInstantiator.<init>(ReflectionInstantiator.java:36)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.createInstantiator(ViewTypeObjectBuilderTemplate.java:322)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:289)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applySubviewMapping(ViewTypeObjectBuilderTemplate.java:576)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.applyMapping(ViewTypeObjectBuilderTemplate.java:521)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:243)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate.<init>(ViewTypeObjectBuilderTemplate.java:118)
	at com.blazebit.persistence.view.impl.objectbuilder.ViewTypeObjectBuilderTemplate$Key.createValue(ViewTypeObjectBuilderTemplate.java:1105)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.getTemplate(EntityViewManagerImpl.java:344)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.createObjectBuilder(EntityViewManagerImpl.java:317)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applyObjectBuilder(EntityViewManagerImpl.java:292)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applyObjectBuilder(EntityViewManagerImpl.java:287)
	at com.blazebit.persistence.view.impl.EntityViewSettingHelper.apply(EntityViewSettingHelper.java:71)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.applySetting(EntityViewManagerImpl.java:180)
	at com.blazebit.persistence.view.testsuite.inheritance.polymorphic.InheritanceMappingInAnotherEntityView.testUsingInheritanceMappingInAnotherEntityView(InheritanceMappingInAnotherEntityView.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javassist.bytecode.DuplicateMemberException: duplicate method: <init> in com.blazebit.persistence.view.testsuite.inheritance.polymorphic.InheritanceMappingInAnotherEntityView$AView_1_BView_$$_javassist_entityview_
	at javassist.bytecode.ClassFile.testExistingMethod(ClassFile.java:680)
	at javassist.bytecode.ClassFile.addMethod(ClassFile.java:656)
	at javassist.CtClassType.addConstructor(CtClassType.java:1315)
	at javassist.CtNewClass.addConstructor(CtNewClass.java:57)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createInheritanceConstructors(ProxyFactory.java:402)
	at com.blazebit.persistence.view.impl.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:336)
	... 43 more
```

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
I have rebased the PR. Given the very obscure byte code generation error, and the fact that I've seen similar mappings work just fine, I kind of assume that the error is related to some sort of mapping issue. But we should debug where this goes wrong and possibly change some error reporting.

**Comment by beikov** [comment]
The automated build fails because the license header and a class java doc with an author definition is missing in `InheritanceMappingInAnotherEntityView.java`. Could you please adapt it so we see the test fail on CI? I'll take a look at the underlying issues meanwhile.

**Comment by JWGmeligMeyling** [comment]
I've added the license header.

**Comment by beikov** [comment]
Superseded by https://github.com/Blazebit/blaze-persistence/pull/488

**Pull request closed without merging**
