### PR TITLE
[#1005] Contradictory where condition generated for multiple TREATs and discriminator column

### PR DESCRIPTION
**Pull request by Mobe91**

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
I have a feeling this is caused by limitations of Hibernate with respect to the implementation of treat. Perhaps this is a good test case where the optimization from #409 should be applied?

**Comment by jwgmeligmeyling** [comment]
@beikov if rewriting TREAT paths to joins is too difficult for now, perhaps we can simply omit them during rendering and rely on the parameter being implicitly accessible through the polymorphism anyway?

**Comment by beikov** [comment]
@jwgmeligmeyling this is an emulation already, but using the implicit downcast feature of HQL. I didn't look too deep yet, but this sounds like a simple bug in the emulation code.

**Comment by beikov** [comment]
Superseded by https://github.com/Blazebit/blaze-persistence/pull/1015

**Pull request closed without merging**
