### PR TITLE
Reproducer for issue #521 (issue not present since Alpha4)

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**

### CODE REVIEW

**Comment by beikov** [comment]
For this test to work properly with DataNucleus, the entity classes need to be top level classes in `src/main/java` that are registered in the `src/main/resources/META-INF/orm.xml`.
I suggest you name the entities something like `SecondaryTableEntityBase` and `SecondaryTableEntitySub` and put them into the package where the other entities are.

**Comment by JWGmeligMeyling** [comment]
Allright! Didn't want to do that directly, because it would potentially cause all tests to fail rather than just the reproducer, but it should just pass now anyway.

**Comment by beikov** [comment]
Yeah it passed for Hibernate 5.2 and EclipseLink already, so it's probably fine.

**Comment by JWGmeligMeyling** [comment]
I've moved the files to `src/main/java`. It however doesn't seem to pass locally, I think I missed something in `persistence.xml` but I can't seem to find it.

**Comment by beikov** [comment]
Looks fine to me. Let's see what Travis CI reports.

**Comment by beikov** [comment]
Ahh, the test class needs to specify the entity classes it uses by providing them via an overridden `getEntityClasses`. These classes are registered in the persistence unit. The orm.xml is just for enhancers to know which classes to enhance.

**Comment by JWGmeligMeyling** [comment]
Fixed 😄 Thought it wouldn't be necessary if the entities were already listed in the test `persistence.xml`.

**Comment by JWGmeligMeyling** [comment]
Is the test suite failing in general or did I miss something?

**Comment by beikov** [comment]
It's a checkstyle error because of the use of a `.*` import: https://travis-ci.org/Blazebit/blaze-persistence/jobs/348301799

**Comment by JWGmeligMeyling** [comment]
Annoying IDE configs all the time! :)

**Pull request merged**
