### PR TITLE
Update Hibernate and Quarkus version

### PR DESCRIPTION
**Pull request by beikov**
This is just a WIP to trigger the CI

### CODE REVIEW

**Comment by jwgmeligmeyling** [comment]
Sad to see that `Issue950Test.testJoinOrderWithRightJoinWithInnerImplicitJoins` and `SubqueryTest.testMultipleCorrelationsWithJoins` broke. Seems that there has been a regression in Hibernate 😉  Any clue which PR might have caused it?

**Comment by beikov** [comment]
Yeah pretty sad, but no, no clue yet. If have any idea what the cause could be, that would be very helpful. I dug into this a week ago, but had to do some other things. I hope I can get to it though in the next days.

**Comment by jwgmeligmeyling** [comment]
I have ported the test cases in `Issue950Test` to the Hibernate test suite: https://github.com/hibernate/hibernate-orm/compare/master...jwgmeligmeyling:reproducers-blaze-persisence-1237?expand=1

All of them are passing except for the two queries relying on implicit joins obviously. Unfortunately, the regression occurs in one of the tests with an implicit join. Therefore we probably have to mimic the implicit join in the HQL query to reproduce the issue.

How would you expect the implicit joins in this query to be added?

```sql
SELECT COALESCE(a.key, b.key, c.key, d.key), a.value, b.value, c.value, d.value 
FROM A a
INNER JOIN B b ON a.key = b.key AND a.association.value = b.association.value 
RIGHT JOIN C c ON a.key = c.key AND a.association.value = c.association.value
INNER JOIN D d ON d.key = c.key AND d.association.value = c.association.value
ORDER BY COALESCE(a.key, b.key, c.key, d.key) ASC
```

**Comment by jwgmeligmeyling** [comment]
Nevermind, I found the appropiate HQL using `CriteriaBuilder#getQueryString`. I've pushed the reproducing commit to the aforementioned branch.

The HQL is:

```sql
SELECT COALESCE(a.key,b.key,c.key,d.key) AS key, a.value AS aValue, b.value AS bValue, c.value AS cValue, d.value AS dValue 
FROM A a JOIN a.association association_1
JOIN B b ON (EXISTS (SELECT 1 FROM b.association _synth_subquery_0 WHERE a.key = b.key AND association_1.value = _synth_subquery_0.value)) 
RIGHT JOIN C c ON (EXISTS (SELECT 1 FROM c.association _synth_subquery_0 WHERE a.key = c.key AND association_1.value = _synth_subquery_0.value))
JOIN c.association association_5 
JOIN D d ON (EXISTS (SELECT 1 FROM d.association _synth_subquery_0 WHERE d.key = c.key AND _synth_subquery_0.value = association_5.value))
ORDER BY COALESCE(a.key,b.key,c.key,d.key) ASC
```

The current Hibernate master produces the following SQL for the query:

```sql
    select
        coalesce(outerjoint0_.key_id,
        outerjoint2_.key_id,
        outerjoint4_.key_id,
        outerjoint7_.key_id) as col_0_0_,
        outerjoint0_.value as col_1_0_,
        outerjoint2_.value as col_2_0_,
        outerjoint4_.value as col_3_0_,
        outerjoint7_.value as col_4_0_ 
    from
        a outerjoint0_ 
    inner join
        association outerjoint1_ 
            on outerjoint0_.association_key_id=outerjoint1_.key_id 
    inner join
        b outerjoint2_ 
            on (
                exists (
                    select
                        1 
                from
                    association outerjoint3_ 
                where
                    outerjoint2_.association_key_id=outerjoint3_.key_id 
                    and outerjoint0_.key_id=outerjoint2_.key_id 
                    and outerjoint1_.value=outerjoint3_.value
            )
        ) cross 
    join
        association outerjoint3_ 
    right outer join
        c outerjoint4_ 
            on (
                exists (
                    select
                        1 
                from
                    association outerjoint5_ 
                where
                    outerjoint4_.association_key_id=outerjoint5_.key_id 
                    and outerjoint0_.key_id=outerjoint4_.key_id 
                    and outerjoint1_.value=outerjoint5_.value
            )
        ) cross 
    join
        association outerjoint5_ 
    inner join
        association outerjoint6_ 
            on outerjoint4_.association_key_id=outerjoint6_.key_id 
    inner join
        d outerjoint7_ 
            on (
                exists (
                    select
                        1 
                from
                    association outerjoint8_ 
                where
                    outerjoint7_.association_key_id=outerjoint8_.key_id 
                    and outerjoint7_.key_id=outerjoint4_.key_id 
                    and outerjoint8_.value=outerjoint6_.value
            )
        ) cross 
    join
        association outerjoint8_ 
    where
        outerjoint2_.association_key_id=outerjoint3_.key_id 
        and outerjoint4_.association_key_id=outerjoint5_.key_id 
        and outerjoint7_.association_key_id=outerjoint8_.key_id 
    order by
        coalesce(outerjoint0_.key_id,
        outerjoint2_.key_id,
        outerjoint4_.key_id,
        outerjoint7_.key_id) ASC
```

Hibernate 5.4.10.Final instead produced:

```sql
    select
        coalesce(outerjoint0_.key_id,
        outerjoint2_.key_id,
        outerjoint4_.key_id,
        outerjoint7_.key_id) as col_0_0_,
        outerjoint0_.value as col_1_0_,
        outerjoint2_.value as col_2_0_,
        outerjoint4_.value as col_3_0_,
        outerjoint7_.value as col_4_0_ 
    from
        a outerjoint0_ 
    inner join
        association outerjoint1_ 
            on outerjoint0_.association_key_id=outerjoint1_.key_id 
    inner join
        b outerjoint2_ 
            on (
                exists (
                    select
                        1 
                from
                    association outerjoint3_ 
                where
                    outerjoint2_.association_key_id=outerjoint3_.key_id 
                    and outerjoint0_.key_id=outerjoint2_.key_id 
                    and outerjoint1_.value=outerjoint3_.value
            )
        ) 
    right outer join
        c outerjoint4_ 
            on (
                exists (
                    select
                        1 
                from
                    association outerjoint5_ 
                where
                    outerjoint4_.association_key_id=outerjoint5_.key_id 
                    and outerjoint0_.key_id=outerjoint4_.key_id 
                    and outerjoint1_.value=outerjoint5_.value
            )
        ) 
    inner join
        association outerjoint6_ 
            on outerjoint4_.association_key_id=outerjoint6_.key_id 
    inner join
        d outerjoint7_ 
            on (
                exists (
                    select
                        1 
                from
                    association outerjoint8_ 
                where
                    outerjoint7_.association_key_id=outerjoint8_.key_id 
                    and outerjoint7_.key_id=outerjoint4_.key_id 
                    and outerjoint8_.value=outerjoint6_.value
            )
        ) 
    order by
        coalesce(outerjoint0_.key_id,
        outerjoint2_.key_id,
        outerjoint4_.key_id,
        outerjoint7_.key_id) ASC
```

The diff is:

```diff
--- scratch_1.sql       2020-12-19 13:41:54.564813500 +0100
+++ scratch.sql 2020-12-19 13:33:45.997046700 +0100
@@ -25,7 +25,9 @@
                   and outerjoint0_.key_id=outerjoint2_.key_id
                   and outerjoint1_.value=outerjoint3_.value
             )
-        )
+        ) cross
+            join
+    association outerjoint3_
         right outer join
     c outerjoint4_
     on (
@@ -39,7 +41,9 @@
                   and outerjoint0_.key_id=outerjoint4_.key_id
                   and outerjoint1_.value=outerjoint5_.value
             )
-        )
+        ) cross
+            join
+    association outerjoint5_
         inner join
     association outerjoint6_
     on outerjoint4_.association_key_id=outerjoint6_.key_id
@@ -56,7 +60,13 @@
                   and outerjoint7_.key_id=outerjoint4_.key_id
                   and outerjoint8_.value=outerjoint6_.value
             )
-        )
+        ) cross
+            join
+    association outerjoint8_
+where
+        outerjoint2_.association_key_id=outerjoint3_.key_id
+  and outerjoint4_.association_key_id=outerjoint5_.key_id
+  and outerjoint7_.association_key_id=outerjoint8_.key_id
 order by
     coalesce(outerjoint0_.key_id,
              outerjoint2_.key_id,
```

I think its a regression that may be caused by https://github.com/hibernate/hibernate-orm/commit/b24a3cbf2d6387a74ade4fc04021b9bfe6869c91 (HHH-14279 Fix join ordering issue that happens for entity key joins when using a WITH/ON clause) in 5.4.24.

**Comment by jwgmeligmeyling** [comment]
The reproducer passes in 5.4.23, thus the issue was introduced with 5.4.24 making HHH-14279 a likely cause. I have created https://hibernate.atlassian.net/browse/HHH-14381 for it.

**Comment by beikov** [comment]
Thanks for the reproducer, I debugged the problem independently yesterday and already have a fix, yet I had no testcase for Hibernate yet. Thanks to you, we now also have a test case. Great work!

**Comment by jwgmeligmeyling** [comment]
Cool! Thanks for being able to look into the issue so quickly!

**Comment by beikov** [comment]
I'll close this now as the issue was fixed via https://hibernate.atlassian.net/browse/HHH-14380 which should be released next week as 5.4.27.Final

**Pull request closed without merging**
