### PR TITLE
Add Spring Boot 2.2 test profile

### PR DESCRIPTION
**Pull request by heruan**
## Description
Add a test profile for Spring Boot 2.2

## Related Issue
(Issues will be added here if there's something to fix)

## Motivation and Context
Spring Boot 2.2 is about to be released and it brings Hibernate 5.4

### CODE REVIEW

**Comment by beikov** [comment]
You would also have to add an entry to the travis.yml file so that the new profile is executed

**Comment by heruan** [comment]
Is this sufficient?

```diff
     - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 SPRING_DATA=spring-data-2.1.x DELTASPIKE=deltaspike-1.8
       jdk: oraclejdk8
+    - env: JPAPROVIDER=hibernate-5.2 RDBMS=h2 SPRING_DATA=spring-data-2.2.x DELTASPIKE=deltaspike-1.8
+      jdk: oraclejdk8
```

**Comment by beikov** [comment]
You can, but I don't think that you are required to use Hibernate 5.4. Let's do it anyway.

**Comment by JWGmeligMeyling** [comment]
You'll probably need this commit too from my PR: https://github.com/Blazebit/blaze-persistence/pull/843/commits/1d8bd6a1914bafd999c185b791a6a41f01232de1

**Comment by beikov** [comment]
I'll move these changes from here over to https://github.com/Blazebit/blaze-persistence/pull/843

**Pull request closed without merging**
