### PR TITLE
reproducer for [#1670]

### PR DESCRIPTION
**Pull request by david-kubecka**

### CODE REVIEW

**Comment by beikov** [comment]
Also, please rebase this here @david-kubecka

**Comment by david-kubecka** [comment]
@beikov I've rather updated the issue with link to now merged commit.

**Comment by beikov** [comment]
So is https://github.com/Blazebit/blaze-persistence/issues/1670 also fixed now?

**Comment by david-kubecka** [comment]
As I write in that issue I've made a quick fix which IMO is not very nice and perhaps not working in all cases, though. If you think it's good/safe enough we can close the issue.

**Comment by beikov** [comment]
Gotcha, I'll keep the issue open for now then and think about it a bit more

**Pull request closed without merging**
