### PR TITLE
Test Case for Issue # 1228

### LINKED ISSUE #1228: Tuple query with single scalar select returns same value for each row
Trying to use BlazeCriteriaQuery<Tuple> to return a single attribute, returns expected number of records, however, each record in the list has the same value.
Ex. Person entity with three attributes firstname, lastname, email. Table contains 10 records where 8 have distinct firstnames. Selecting only distinct firstname returns 8 records, but each has same value.

Works fine when Tuple has more than one attributes. 

### Expected behavior
Distinct values for firstname.

### Actual behavior
Same values for firstname in all 8 records.

### Steps to reproduce

```
public class Host {
	@Id
	private Long hostId;
	private String hostName;
	private Long appId;
}

@Override
@Transactional
public List<Map<String, String>> getHosts(String hostName) {
	BlazeCriteriaBuilder cb = BlazeCriteria.get(cbf);
	BlazeCriteriaQuery<Tuple> query = cb.createTupleQuery();
	BlazeRoot<?> root = query.from(Host.class);
	query.select(root.get("hostName")).distinct(true);
	CriteriaBuilder<Tuple> criteriaBuilder = query.createCriteriaBuilder(em);
	List<Tuple> result = criteriaBuilder.getResultList();
	long count = criteriaBuilder.getCountQuery().getSingleResult();
	List<Map<String, String>> hostResults = new ArrayList<Map<String,String>>();
	result.stream().forEach(tuple -> {
		Map<String, String> test = new HashMap<>();
		test.put((String)tuple.get(0), (String)tuple.get(0));
		hostResults.add(test);
	});
	//List has maps with same keys even if the underlying has different values
	return hostResults;
}
```

### Environment
Version:            1.6.0-SNAPSHOT
JPA-Provider:       Hibernate 5.4.l5.Final
DBMS:               Oracle 12c XE
Application Server: Tomcat 9.0.35

### PR DESCRIPTION
**Pull request by riteshka**
## Related Issue

Fixes #1228

### CODE REVIEW

**Comment by beikov** [comment]
Could you please change the commit messages to align with the commit message pattern we have i.e. use the following:

* [#1228] Test case showing tuple query with single scalar select returns same value for each row
* [#1228] Fix issues with tuple query with single scalar select returning same value for each row

Also, please add the a line in the CHANGELOG.md file `* Fix issues with tuple query with single scalar select returning same value for each row`.

**Comment by riteshka** [comment]
Recommended changes to commit messages and changelog.md submitted.

**Comment by beikov** [comment]
Merged via f12818ea458c70d7e82f641791c9087e9cb75e88

**Comment by beikov** [comment]
Thanks for the PR!

**Comment by riteshka** [comment]
Thanks for merging. Appreciate your help.

**Pull request closed without merging**
